//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lenkovec
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALLS
    {
        public string Учеба { get; set; }
        public int Стаж { get; set; }
        public string Телефон { get; set; }
        public string НаименованиеДолжности { get; set; }
        public int Оклад { get; set; }
        public string НаименованиеУчёнойСтепени { get; set; }
        public int Колвочасов { get; set; }
        public Nullable<int> Колвопредметов { get; set; }
        public string Название { get; set; }
        public int Часы { get; set; }
        public string NumГруппы { get; set; }
    }
}
