//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lenkovec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Нагрузка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Нагрузка()
        {
            this.Группа = new HashSet<Группа>();
        }
    
        public int IdНагрузки { get; set; }
        public int Колвочасов { get; set; }
        public Nullable<int> Колвопредметов { get; set; }
        public int КодПредмета { get; set; }
        public int КодПреподавателя { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Группа> Группа { get; set; }
        public virtual Предмет Предмет { get; set; }
        public virtual Преподаватель Преподаватель { get; set; }
    }
}
