//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lenkovec
{
    using System;
    using System.Collections.Generic;
    
    public partial class УчёнаяСтепень
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public УчёнаяСтепень()
        {
            this.Преподаватель = new HashSet<Преподаватель>();
        }
    
        public int IdУчёнойСтепени { get; set; }
        public string НаименованиеУчёнойСтепени { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Преподаватель> Преподаватель { get; set; }
    }
}
